### ISSUE TITLE
[REFACTOR] 🔢 simplify email service to use standard SMTP library

### ISSUE THREAD

**Issue by Sudarsh1010** [keizerworks/keizer-auth#19]
### Description

Currently, the email service has conditional logic to handle different SMTP servers based on the environment. This adds unnecessary complexity and branching paths in the code.

### Changes needed:
- Remove environment-specific conditional checks in SendEmail method
- Use Go's standard smtp library for all environments
- Configure SMTP server details via environment variables:
  - SMTP_HOST
  - SMTP_PORT
  - SMTP_USERNAME (if needed)
  - SMTP_PASSWORD (if needed)
  - EMAIL_FROM

### Expected behavior:
- Single code path for all environments
- SMTP server details configured through .env file
- Production environment will use production SMTP server configured via env vars
- Local development can still use Mailhog by setting appropriate local SMTP values

### Anything else?

- Remove sendEmailUsingMailHog function
- Refactor SendEmail to use a single SMTP implementation
- Update documentation for required environment variables

### Are you willing to submit PR?

No

**Comment by moonpatel** [comment]
completed by #21
