### ISSUE TITLE
[FEAT] :sparkles: Reset Password

### ISSUE THREAD

**Issue by Sudarsh1010** [keizerworks/keizer-auth#9]
### Description

Your should be able to change password by reset password and forgot password 

### Anything else?

[password-reset](https://thecopenhagenbook.com/password-reset)

### Are you willing to submit PR?

No

**Comment by AyushSri5** [comment]
Please assign it to me i am willing it to work on this.

**Comment by King-kin5** [comment]
is this still available
 to work on ?

**Comment by Sudarsh1010** [comment]
yes, want me to assign?

**Comment by King-kin5** [comment]
> yes, want me to assign you?



yes i do

**Comment by Sudarsh1010** [comment]
The project is going to migrated to nestjs (go -> ts ecosystem)
